SchoolWeb/Admin/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Admin.Models
{
    public class Student : BaseEntity
    {
        public int ID { get; set; }

        [Display(Name = "Ad")]
        [Required(ErrorMessage ="Ad daxil edin")]
        public string Name { get; set; }

        [Display(Name = "Soyad")]
        [Required(ErrorMessage = "Soyad daxil edin")]
        public string Surname { get; set; }

        [Display(Name = "Ünvan")]
        [Required(ErrorMessage = "Ünvan daxil edin")]
        public string Address { get; set; }

        [Display(Name = "Doğum günü")]
        [Required(ErrorMessage = "Tarix daxil edin")]
        public DateTime DateOfBirth { get; set; }

        [Display(Name = "Sinif Nömrəsi")]
        [Required(ErrorMessage = "Sinif daxil edin")]
        public int? ClassID { get; set; }

        public byte[] Image { get; set; }

        [ForeignKey("ClassID")]
        public virtual TableClass TableClass { get; set; }
        public virtual ICollection<Mark> Mark { get; set; }
    }
}

SchoolWeb/Admin/Controllers/MarkController.cs
using Admin.Constants;
using Admin.Models;
using Admin.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Admin.Controllers
{
    [Authorize(Roles = "Admin,User,Teacher")]
    public class MarkController : Controller
    {
        DataContext ctx = new DataContext();
        // GET: Mark
        public ActionResult Index()
        {
                var marks = ctx.Marks.Where(m=>m.Status==Enums.Status.Active).ToList();
                return View(marks);  
        }

        public ActionResult Create()
        {
            var model = new StudentsMarkViewModel()
            {
                students = ctx.Students.Where(s => s.Status==Enums.Status.Active).ToList(),
                mark=new Mark()
            };
            return View("MarkForm",model);
        }

        public ActionResult Update(int id)
        {
            var model = new StudentsMarkViewModel()
            {
                students=ctx.Students.ToList(),
                mark=ctx.Marks.FirstOrDefault(x=>x.ID==id)
            };
            return View("MarkForm", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Mark mark)
        {
            if (!ModelState.IsValid)
            {
                var model = new StudentsMarkViewModel()
                {
                    students=ctx.Students.ToList(),
                    mark=mark
                };
                return View("MarkForm", model);
            }
            if (mark.ID==0)
            {
                mark.Status = Enums.Status.Active;
                mark.CreatedDate = DateTime.Now;
                ctx.Marks.Add(mark);
            }
            else
            {
                mark.CreatedDate = DateTime.Now;
                ctx.Entry(mark).State = EntityState.Modified;
            }
            ctx.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var deletedmark = ctx.Marks.FirstOrDefault(x => x.ID == id);
            deletedmark.Status = Enums.Status.Deleted;
            ctx.Entry(deletedmark).State = EntityState.Modified;
            ctx.SaveChanges();
            return RedirectToAction("index");
        }

        public ActionResult ShowsMarks(int id)
        {
            using (var ctx=new DataContext())
            {
                var marks = ctx.Marks.Where(m => m.StudentID == id && m.Status == Enums.Status.Active).ToList();
                return PartialView(marks);
            }
            
        }
    }
}

SchoolWeb/Admin/Controllers/StudentController.cs
using Admin.Constants;
using Admin.Models;
using Admin.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace Admin.Controllers
{
    [Authorize(Roles = "Admin,User,Teacher")]
    public class StudentController : Controller
    {
        DataContext ctx = new DataContext();
        public ActionResult Index()
        {
            var students = ctx.Students.Where(s => s.Status == Enums.Status.Active).ToList();
            return View(students);
        }

        public ActionResult ShowsStudents(int id)
        {
            var students = ctx.Students.Where(x => x.ClassID == id && x.Status == Enums.Status.Active).ToList();
            return PartialView(students);
        }

        public ActionResult Create()
        {
            var model = new StudentClassViewModel()
            {
                Classes = ctx.TableClasses.Where(x => x.Status == Enums.Status.Active).ToList(),
                Student = new Student()
            };
            return View(model);
        }

        public ActionResult Update(int id)
        {
            var student = ctx.Students.FirstOrDefault(x => x.ID == id);
            if (student == null)
                return HttpNotFound();

            var model = new StudentClassViewModel()
            {
                Classes = ctx.TableClasses.ToList(),
                Student = student
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Student student, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                var model = new StudentClassViewModel()
                {
                    Classes = ctx.TableClasses.ToList(),
                    Student = student
                };
                return View("Create", model);
            }
            if (student.ID == 0)
            {
                if (file != null && file.ContentLength > 0)
                {
                    student.Image = new byte[file.ContentLength];
                    file.InputStream.Read(student.Image, 0, file.ContentLength);
                    student.Status = Enums.Status.Active;
                    student.CreatedDate = DateTime.Now;
                    ctx.Students.Add(student);
                }
                else
                {
                    ViewBag.message = "Şəkil daxil edilməlidir";
                    var model = student;
                    return View("Create", model);
                }

            }
            else if (!ModelState.IsValid)
            {
                var model = new StudentClassViewModel()
                {
                    Classes = ctx.TableClasses.ToList(),
                    Student = student
                };
                return View("Update", model);
            }
            else if (file != null && file.ContentLength > 0)
            {
                student.Image = new byte[file.ContentLength];
                file.InputStream.Read(student.Image, 0, file.ContentLength);
                student.CreatedDate = DateTime.Now;
                ctx.Entry(student).State = EntityState.Modified;
            }
            else
            {
                student.CreatedDate = DateTime.Now;
                ctx.Entry(student).State = EntityState.Modified;
            }
            ctx.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var deletedstudent = ctx.Students.FirstOrDefault(x => x.ID == id);
            deletedstudent.Status = Enums.Status.Deleted;
            ctx.Entry(deletedstudent).State = EntityState.Modified;
            ctx.SaveChanges();
            return RedirectToAction("index");
        }
    }
}

SchoolWeb/Admin/Views/Student/Create.cshtml
@model Admin.ViewModels.StudentClassViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

@using (Html.BeginForm("Save", "Student", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="content container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    @Html.LabelFor(m => m.Student.Name)
                    @Html.TextBoxFor(m => m.Student.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Student.Name)
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Student.Surname)
                    @Html.TextBoxFor(m => m.Student.Surname, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Student.Surname)
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Student.ClassID)
                    @Html.DropDownListFor(m => m.Student.ClassID, new SelectList(Model.Classes, "ID", "ClassNo"), "Sinif seçin", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Student.ClassID)
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Student.Address)
                    @Html.TextBoxFor(m => m.Student.Address, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Student.Address)
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Student.DateOfBirth)
                    @Html.TextBoxFor(m => m.Student.DateOfBirth, new { @class = "form-control", type = "date" })
                    @Html.ValidationMessageFor(m => m.Student.DateOfBirth)
                </div>

                <button type="submit" class="btn btn-primary">Yadda saxla</button>
                @Html.AntiForgeryToken()
            </div>
            <div class="col-sm-6">
                <img src="~/Content/Images/student.png" width="150" />
                <div class="editor-field">
                    <input type="file" name="file" id="file" />
                </div>
                <p style="color:red;">@ViewBag.message</p>
            </div>
        </div>
    </div>
}


@section validate{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

SchoolWeb/Admin/Views/Student/Index.cshtml
@model List<Admin.Models.Student>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="content container-fluid">
    <div class="row">
        <div class="col-sm-12">
            @if (User.IsInRole("Admin"))
            {
                @Html.ActionLink("Yeni Şagird", "Create", null, new { @class = "btn btn-success Addbtn" })

            }
            <table id="dttable" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>İD</th>
                        <th>Adı</th>
                        <th>Soyadı</th>
                        <th>Doğum Günü</th>
                        <th>Ünvan</th>
                        <th>Sinif</th>
                        <th>Şəkil</th>
                        @if (User.IsInRole("Admin"))
                        {
                            <th></th>
                        }
                        <th></th>
                    </tr>
                </thead>

                <tfoot>
                    <tr>
                        <th>İD</th>
                        <th>Adı</th>
                        <th>Soyadı</th>
                        <th>Doğum Günü</th>
                        <th>Ünvan</th>
                        <th>Sinif</th>
                        <th>Şəkil</th>
                        @if (User.IsInRole("Admin"))
                        {
                            <th></th>
                        }
                        <th></th>
                    </tr>
                </tfoot>

                <tbody>
                    @foreach (var student in Model)
                    {
                    <tr>
                        <td>@student.ID</td>
                        <td>@student.Name</td>
                        <td>@student.Surname</td>
                        <td>@student.DateOfBirth.ToShortDateString()</td>
                        <td>@student.Address</td>
                        <td>@student.TableClass.ClassNo</td>
                        <td>
                            @{
                                var base64 = Convert.ToBase64String(student.Image);
                                var imgsrc = String.Format("data:image/png;base64,{0}", base64);
                            }
                            <img src="@imgsrc" width="55" height="55" style="margin-left:20px;" />
                        </td>
                        @if (User.IsInRole("Admin"))
                        {
                            <td>
                                <a href="@Url.Action("Update","Student",new {id=student.ID })" class="btn btn-primary btn-sm" style="color:white"><i class="fa fa-pen fa-sm"></i></a>
                                <a data-id="@student.ID" class="btn btn-danger btn-sm js-delete" style="color:white"><i class="fa fa-trash fa-sm"></i></a>
                            </td>
                        }
                        <td>
                            @Ajax.ActionLink("Qiymət", "ShowsMarks", "Mark", new { id = student.ID }, new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "MarkList" }, new { @class = "btn btn-primary" })
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
            <div id="MarkList"></div>
        </div>
    </div>
</div>

@section styles{
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
}

@section scripts{
    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>*@
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/Scripts/MyDataTable.js"></script>
    <script>
        $(document).ready(function () {
            $("#dttable ").on("click",".js-delete",function () {
                var button = $(this);
                bootbox.confirm("Bu məlumatı silməyə əminsinizmi?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "/student/Delete/" + button.attr("data-id"),
                            method: "GET",
                            success: function () {
                                button.parents("tr").remove();
                            }
                        });
                    }
                });
            });
        });
    </script>
}

SchoolWeb/Admin/Views/Student/ShowsStudents.cshtml
@model IEnumerable<Admin.Models.Student>

<h1>Şagirdlərin siyahısı</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>İD</th>
            <th>Ad</th>
            <th>Soyad</th>
            <th>Doğum Günü</th>
            <th>Ünvan</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var student in Model)
        {
        <tr>
            <td>@student.ID</td>
            <td>@student.Name</td>
            <td>@student.Surname</td>
            <td>@student.DateOfBirth</td>
            <td>@student.Address</td>
            <td>
                <a href="@Url.Action("Update","Student",new {id=student.ID })" class="btn btn-primary btn-sm" style="color:white"><i class="fa fa-pen fa-sm"></i></a>
                <a href="@Url.Action("Delete","Student",new {id=student.ID })" class="btn btn-danger btn-sm" style="color:white"><i class="fa fa-trash fa-sm"></i></a>
            </td>
        </tr>
        }
    </tbody>
</table>

SchoolWeb/Admin/Views/Student/Update.cshtml
@model Admin.ViewModels.StudentClassViewModel
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

@using (Html.BeginForm("Save", "Student", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="content container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    @Html.HiddenFor(m=>m.Student.Image)
                    @Html.LabelFor(m => m.Student.Name)
                    @Html.TextBoxFor(m => m.Student.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Student.Name)
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Student.Surname)
                    @Html.TextBoxFor(m => m.Student.Surname, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Student.Surname)
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Student.ClassID)
                    @Html.DropDownListFor(m => m.Student.ClassID, new SelectList(Model.Classes, "ID", "ClassNo"), "Sinif seçin", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Student.ClassID)
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Student.Address)
                    @Html.TextBoxFor(m => m.Student.Address, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Student.Address)
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Student.DateOfBirth)
                    @Html.TextBoxFor(m => m.Student.DateOfBirth, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
                    @Html.ValidationMessageFor(m => m.Student.DateOfBirth)
                </div>
                @Html.HiddenFor(m => m.Student.ID)
                @Html.AntiForgeryToken()
                <button type="submit" class="btn btn-primary">Yadda saxla</button>
            </div>
            <div class="col-sm-6">

                @{
                    var base64 = Convert.ToBase64String(Model.Student.Image);
                    var imgsrc = String.Format("data:image/png;base64,{0}", base64);
                }
                <img src="@imgsrc" width="150" />
                <div class="editor-field">
                    <input class="valid" aria-invalid="false" type="file" name="file" id="file" />
                </div>
            </div>
        </div>
    </div>
}

@section validate{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}