SchoolWeb/Admin/Models/Teacher.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Admin.Models
{
    public class Teacher : BaseEntity
    {
        public int ID { get; set; }

        [Display(Name = "Ad")]
        [Required(ErrorMessage ="Ad daxil edilməlidir")]
        public string Name { get; set; }

        [Display(Name = "Soyad")]
        [Required(ErrorMessage = "Soyad daxil edilməlidir")]
        public string Surname { get; set; }

        [Display(Name = "Doğum günü")]
        [Required(ErrorMessage = "Doğum tarixi daxil edilməlidir")]
        public DateTime DateOfBirth { get; set; }

        [Display(Name = "Maaş")]
        [Range(300,5000,ErrorMessage ="Maaş 300 və 5000 aralığında olmalıdır")]
        [Required(ErrorMessage = "Maaş daxil edilməlidir")]
        public int? Salary { get; set; }

        [Display(Name = "Ünvan")]
        [Required(ErrorMessage = "Ünvan daxil edilməlidir")]
        public string Address { get; set; }

        [Display(Name = "Fənn")]
        [Required(ErrorMessage = "Fənn daxil edilməlidir")]
        public string Subject { get; set; }

        public byte[] Image { get; set; }
    }
}

SchoolWeb/Admin/Controllers/TeacherController.cs
using Admin.Constants;
using Admin.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Admin.Controllers
{
    [Authorize(Roles = "Admin,User,Teacher")]
    public class TeacherController : Controller
    {
        // GET: Teacher
        public ActionResult Index()
        {
            using (var ctx=new DataContext())
            {
                var teachers = ctx.Teachers.Where(t => t.Status == Enums.Status.Active).ToList();
                return View(teachers);
            }
        }

        public ActionResult Create()
        {
             return View();
        }

        public ActionResult Update(int id)
        {
            using (var ctx=new DataContext())
            {
                var teacher = ctx.Teachers.FirstOrDefault(x => x.ID == id);
                return View(teacher);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Teacher teacher,HttpPostedFileBase file)
        {
            using (var ctx=new DataContext())
            {
                if (!ModelState.IsValid)
                {
                    var model = teacher;
                    return View("Create", model);
                }
                if (teacher.ID==0)
                {
                    if (file != null && file.ContentLength > 0)
                    {
                        teacher.Image = new byte[file.ContentLength];
                        file.InputStream.Read(teacher.Image, 0, file.ContentLength);
                        teacher.Status = Enums.Status.Active;
                        teacher.CreatedDate = DateTime.Now;
                        ctx.Teachers.Add(teacher);
                    }
                    else
                    {
                        ViewBag.message = "Şəkil daxil edilməlidir";
                        var model = teacher;
                        return View("Create", model);
                    }
                }
                else if (!ModelState.IsValid)
                {
                    var model = teacher;
                    return View("Update", model);
                }
                else if(file!=null&&file.ContentLength > 0)
                {
                    teacher.Image = new byte[file.ContentLength];
                    file.InputStream.Read(teacher.Image, 0, file.ContentLength);
                    teacher.CreatedDate = DateTime.Now;
                    ctx.Entry(teacher).State = EntityState.Modified;
                }
                else
                {
                    teacher.CreatedDate = DateTime.Now;
                    ctx.Entry(teacher).State = EntityState.Modified;
                }
                ctx.SaveChanges();
                return RedirectToAction("index");
            }
        }

        public ActionResult Delete(int id)
        {
            using (var ctx=new DataContext())
            {
                var deletedteacher = ctx.Teachers.FirstOrDefault(x => x.ID == id);
                deletedteacher.Status = Enums.Status.Deleted;
                ctx.Entry(deletedteacher).State = EntityState.Modified;
                ctx.SaveChanges();
            }
            return RedirectToAction("index");
        }
    }
}

SchoolWeb/Admin/Controllers/TeachersClassesController.cs
using Admin.Constants;
using Admin.Models;
using Admin.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace Admin.Controllers
{
    [Authorize(Roles = "Admin,User,Teacher")]
    public class TeachersClassesController : Controller
    {
        DataContext ctx = new DataContext();
        // GET: StudentsClasses
        public ActionResult Index()
        {
            var teacherclasses = ctx.TeachersClasses.ToList();
            return View(teacherclasses);
        }
        public ActionResult ShowTeachers(int id)
        {
            var teachersclasses = ctx.TeachersClasses.Where(x => x.ClassID == id).ToList();
            return PartialView(teachersclasses);
        }

        public ActionResult ShowClasses(int id)
        {
            var teachersclasses = ctx.TeachersClasses.Where(x => x.TeacherID == id).ToList();
            return PartialView(teachersclasses);
        }

        public ActionResult Create()
        {
            var model = new TeachersClassesViewModel()
            {
                tableclasses = ctx.TableClasses.Where(x => x.Status == Enums.Status.Active).ToList(),
                teachers = ctx.Teachers.Where(x => x.Status == Enums.Status.Active).ToList(),
                teachersClasses=new TeachersClasses()
            };
            return View("TeachersForm",model);
        }

        public ActionResult Update(int id)
        {
            var model = new TeachersClassesViewModel()
            {
                teachers = ctx.Teachers.ToList(),
                tableclasses = ctx.TableClasses.ToList(),
                teachersClasses = ctx.TeachersClasses.FirstOrDefault(x => x.ID == id)
            };
            return View("TeachersForm", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(TeachersClasses teachersclasses)
        {
            if (!ModelState.IsValid)
            {
                var model = new TeachersClassesViewModel()
                {
                    teachers=ctx.Teachers.ToList(),
                    tableclasses=ctx.TableClasses.ToList()
                };
                return View("TeachersForm");
            }
            if (teachersclasses.ID == 0)
            {
                ctx.TeachersClasses.Add(teachersclasses);
            }
            else
            {
                ctx.Entry(teachersclasses).State = EntityState.Modified;
            }
            ctx.SaveChanges();
            return RedirectToAction("index");
        }

        public ActionResult Delete(int id)
        {
            var deletedteacherclasses = ctx.TeachersClasses.FirstOrDefault(x => x.ID == id);
            ctx.TeachersClasses.Remove(deletedteacherclasses);
            ctx.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

SchoolWeb/Admin/Views/Teacher/Create.cshtml
@model Admin.Models.Teacher
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

@using (Html.BeginForm("Save", "Teacher", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="content container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    @Html.LabelFor(m => m.Name)
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Name)
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Surname)
                    @Html.TextBoxFor(m => m.Surname, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Surname)
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Address)
                    @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Address)
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.DateOfBirth)
                    @Html.TextBoxFor(m => m.DateOfBirth, new { @class = "form-control", type = "date" })
                    @Html.ValidationMessageFor(m => m.DateOfBirth)
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Salary)
                    @Html.TextBoxFor(m => m.Salary, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Salary)
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Subject)
                    @Html.TextBoxFor(m => m.Subject, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Subject)
                </div>
                <button type="submit" class="btn btn-primary">Yadda saxla</button>
                @Html.AntiForgeryToken()
            </div>
            <div class="col-sm-6">
                <img src="~/Content/Images/linux-add-user.jpg" width="150" />
                <div class="editor-field">
                    <input type="file" name="file" id="file" />
                </div>
                <p style="color:red;">@ViewBag.message</p>
            </div>
        </div>
    </div>
}

@section validate{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

SchoolWeb/Admin/Views/Teacher/Index.cshtml
@model List<Admin.Models.Teacher>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="content container-fluid">
    <div class="row">
        <div class="col-sm-12">
            @if (User.IsInRole("Admin"))
            {
                @Html.ActionLink("Yeni Müəllim", "Create", null, new { @class = "btn btn-success Addbtn" })
            }
            <table id="dttable" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>İD</th>
                        <th>Ad</th>
                        <th>Soyad</th>
                        <th>Doğum Günü</th>
                        <th>Ünvan</th>
                        <th>Maaş</th>
                        <th>Fənn</th>
                        <th>Şəkil</th>
                        @if (User.IsInRole("Admin"))
                        {
                            <th></th>
                        }
                        <th></th>
                    </tr>
                </thead>

                <tfoot>
                    <tr>
                        <th>İD</th>
                        <th>Ad</th>
                        <th>Soyad</th>
                        <th>Doğum Günü</th>
                        <th>Ünvan</th>
                        <th>Maaş</th>
                        <th>Fənn</th>
                        <th>Şəkil</th>
                        @if (User.IsInRole("Admin"))
                        {
                            <th></th>
                        }
                        <th></th>
                    </tr>
                </tfoot>

                <tbody>
                    @foreach (var teacher in Model)
                    {
                    <tr>
                        <td>@teacher.ID</td>
                        <td>@teacher.Name</td>
                        <td>@teacher.Surname</td>
                        <td>@teacher.DateOfBirth.ToShortDateString()</td>
                        <td>@teacher.Address</td>
                        <td>@teacher.Salary</td>
                        <td>@teacher.Subject</td>
                        <td>
                            @{
                                var base64 = Convert.ToBase64String(teacher.Image);
                                var imgsrc = String.Format("data:image/png;base64,{0}", base64);
                            }
                            <img src="@imgsrc" width="55" height="55" style="margin-left:20px;" />
                        </td>
                        @if (User.IsInRole("Admin"))
                        {
                            <td>
                                <a href="@Url.Action("Update","Teacher",new {id=teacher.ID })" class="btn btn-primary btn-sm" style="color:white"><i class="fa fa-pen fa-sm"></i></a>
                                <a data-id="@teacher.ID" class="btn btn-danger btn-sm js-delete" style="color:white"><i class="fa fa-trash fa-sm"></i></a>
                            </td>
                        }
                        <td>
                            @Ajax.ActionLink("Siniflər", "ShowClasses", "TeachersClasses", new { id = teacher.ID }, new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "ClassList" }, new { @class = "btn btn-primary" })
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
            <div id="ClassList"></div>
        </div>
    </div>
</div>

@section styles{
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
}

@section scripts{
    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>*@
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/Scripts/MyDatatable.js"></script>
    <script>
        $(document).ready(function () {
            $("#dttable ").on("click", ".js-delete", function () {
                var button = $(this);
                bootbox.confirm("Bu məlumatı silməyə əminsinizmi?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "/teacher/Delete/" + button.attr("data-id"),
                            method: "GET",
                            success: function () {
                                button.parents("tr").remove();
                            }
                        });
                    }
                });
            });
        });
    </script>
}

SchoolWeb/Admin/Views/Teacher/Update.cshtml
@model Admin.Models.Teacher
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

@using (Html.BeginForm("Save", "Teacher", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="content container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    @Html.LabelFor(m => m.Name)
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Name)
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Surname)
                    @Html.TextBoxFor(m => m.Surname, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Surname)
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Address)
                    @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Address)
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.DateOfBirth)
                    @Html.TextBoxFor(m => m.DateOfBirth, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
                    @Html.ValidationMessageFor(m => m.DateOfBirth)
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Salary)
                    @Html.TextBoxFor(m => m.Salary, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Salary)
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Subject)
                    @Html.TextBoxFor(m => m.Subject, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Subject)
                </div>
                @Html.HiddenFor(m => m.ID)
                @Html.HiddenFor(m => m.Image)
                @Html.AntiForgeryToken()
                <button type="submit" class="btn btn-primary">Yadda saxla</button>
            </div>
            <div class="col-sm-6">
                @{
                    var base64 = Convert.ToBase64String(Model.Image);
                    var imgsrc = String.Format("data:image/png;base64,{0}", base64);
                }
                <img src="@imgsrc" width="150" />
                <div class="editor-field">
                    <input type="file" name="file" id="file" />
                </div>
            </div>
        </div>
    </div>
}

@section validate{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}