SchoolWeb/Admin/Controllers/TrashController.cs
using Admin.Constants;
using Admin.Models;
using Admin.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TrashController : Controller
    {
        DataContext ctx = new DataContext();
        // GET: Trash
        public ActionResult Index()
        {
            var model = new StudentsTeachersMarksViewModel()
            {
                Students = ctx.Students.Where(s => s.Status == Enums.Status.Deleted).ToList(),
                Teachers = ctx.Teachers.Where(t => t.Status == Enums.Status.Deleted).ToList(),
                Marks = ctx.Marks.Where(m => m.Status == Enums.Status.Deleted).ToList()
            };
            return View(model);
        }

        public ActionResult RecoverStudents(int id)
        {
            var students = ctx.Students.FirstOrDefault(s => s.ID == id);
            students.Status = Enums.Status.Active;
            ctx.Entry(students).State = EntityState.Modified;
            ctx.SaveChanges();
            return RedirectToAction("index");
        }

        public ActionResult RecoverTeachers(int id)
        {
            var teachers = ctx.Teachers.FirstOrDefault(t => t.ID == id);
            teachers.Status = Enums.Status.Active;
            ctx.Entry(teachers).State = EntityState.Modified;
            ctx.SaveChanges();
            return RedirectToAction("index");
        }

        public ActionResult RecoverMarks(int id)
        {
            var marks = ctx.Marks.FirstOrDefault(m => m.ID == id);
            marks.Status = Enums.Status.Active;
            ctx.Entry(marks).State = EntityState.Modified;
            ctx.SaveChanges();
            return RedirectToAction("index");
        }

        [HandleError]
        public ActionResult RemoveStudents(int id)
        {
            var removedstudent = ctx.Students.FirstOrDefault(x => x.ID == id);
            ctx.Students.Remove(removedstudent);
            ctx.SaveChanges();
            return RedirectToAction("index");
        }

        public ActionResult RemoveTeachers(int id)
        {
            var removedteacher = ctx.Teachers.FirstOrDefault(x => x.ID == id);
            ctx.Teachers.Remove(removedteacher);
            ctx.SaveChanges();
            return RedirectToAction("index");
        }

        public ActionResult RemoveMarks(int id)
        {
            var removedmark = ctx.Marks.FirstOrDefault(x => x.ID == id);
            ctx.Marks.Remove(removedmark);
            ctx.SaveChanges();
            return RedirectToAction("index");
        }
    }
}

SchoolWeb/Admin/Views/Trash/DeletedMarks.cshtml
@model List<Admin.Models.Mark>
<div class="content container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <h1>Marks</h1>
            <table id="mark" class="table table-striped table-bordered" style="font-size:13px;">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Azerbaijani</th>
                        <th>Biology</th>
                        <th>Chemistry</th>
                        <th>English</th>
                        <th>Math</th>
                        <th>Geography</th>
                        <th>History</th>
                        <th>Informatics</th>
                        <th>Physics</th>
                        <th>Literature</th>
                        <th>Semester</th>
                        <th>Result</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>

                <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>Azerbaijani</th>
                        <th>Biology</th>
                        <th>Chemistry</th>
                        <th>English</th>
                        <th>Math</th>
                        <th>Geography</th>
                        <th>History</th>
                        <th>Informatics</th>
                        <th>Physics</th>
                        <th>Literature</th>
                        <th>Semester</th>
                        <th>Result</th>
                        <th></th>
                        <th></th>
                    </tr>
                </tfoot>

                <tbody>
                    @foreach (var mark in Model)
                    {
                        <tr>
                            <td>@mark.Student.ID</td>
                            <td>@mark.Azerbaijani</td>
                            <td>@mark.Biology</td>
                            <td>@mark.Chemistry</td>
                            <td>@mark.English</td>
                            <td>@mark.Math</td>
                            <td>@mark.Geography</td>
                            <td>@mark.History</td>
                            <td>@mark.Informatics</td>
                            <td>@mark.Physics</td>
                            <td>@mark.Literature</td>
                            <td>@mark.Semester</td>
                            <td>@mark.Result</td>
                            <td>
                                <a href="@Url.Action("RecoverMarks","Trash",new {id=mark.ID })" class="btn btn-primary btn-sm" style="color:white"><i class="fa fa-undo fa-sm"></i></a>
                            </td>
                            <td>
                                <a data-id="@mark.ID" class="btn btn-danger btn-sm js-delete" style="color:white"><i class="fa fa-trash fa-sm"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

SchoolWeb/Admin/Views/Trash/DeletedStudents.cshtml
@model List<Admin.Models.Student>

<div class="content container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <h1>Şagirdlər</h1>
            <table id="student" class="display table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>İD</th>
                        <th>Adı</th>
                        <th>Soyadı</th>
                        <th>Doğum Günü</th>
                        <th>Ünvan</th>
                        <th>Sinif</th>
                        <th>Şəkil</th>
                        <th></th>
                    </tr>
                </thead>

                <tfoot>
                    <tr>
                        <th>İD</th>
                        <th>Adı</th>
                        <th>Soyadı</th>
                        <th>Doğum Günü</th>
                        <th>Ünvan</th>
                        <th>Sinif</th>
                        <th>Şəkil</th>
                        <th></th>
                    </tr>
                </tfoot>

                <tbody>
                    @foreach (var student in Model)
                    {
                    <tr>
                        <td>@student.ID</td>
                        <td>@student.Name</td>
                        <td>@student.Surname</td>
                        <td>@student.DateOfBirth.ToShortDateString()</td>
                        <td>@student.Address</td>
                        <td>@student.TableClass.ClassNo</td>
                        <td>
                            @{
                                var base64 = Convert.ToBase64String(student.Image);
                                var imgsrc = String.Format("data:image/png;base64,{0}", base64);
                            }
                            <img src="@imgsrc" width="55" height="55" style="margin-left:20px;" />
                        </td>
                        <td>
                            <a href="@Url.Action("RecoverStudents","Trash",new {id=student.ID })" class="btn btn-primary btn-sm" style="color:white"><i class="fa fa-undo fa-sm"></i></a>
                            <a href="@Url.Action("RemoveStudents","Trash",new {id=student.ID })" class="btn btn-danger btn-sm" style="color:white"><i class="fa fa-trash fa-sm"></i></a>
                            @*<a data-id="@student.ID" class="btn btn-danger btn-sm js-delete" style="color:white"><i class="fa fa-trash fa-sm"></i></a>*@
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

SchoolWeb/Admin/Views/Trash/DeletedTeachers.cshtml
@model List<Admin.Models.Teacher>
<div class="content container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <h1>Teachers</h1>
            <table id="teacher" class="display table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>İD</th>
                        <th>Ad</th>
                        <th>Soyad</th>
                        <th>Doğum Günü</th>
                        <th>Ünvan</th>
                        <th>Maaş</th>
                        <th>Fənn</th>
                        <th>Şəkil</th>
                        <th></th>
                    </tr>
                </thead>

                <tfoot>
                    <tr>
                        <th>İD</th>
                        <th>Ad</th>
                        <th>Soyad</th>
                        <th>Doğum Günü</th>
                        <th>Ünvan</th>
                        <th>Maaş</th>
                        <th>Fənn</th>
                        <th>Şəkil</th>
                        <th></th>
                    </tr>
                </tfoot>

                <tbody>
                    @foreach (var teacher in Model)
                    {
                        <tr>
                            <td>@teacher.ID</td>
                            <td>@teacher.Name</td>
                            <td>@teacher.Surname</td>
                            <td>@teacher.DateOfBirth.ToShortDateString()</td>
                            <td>@teacher.Address</td>
                            <td>@teacher.Salary</td>
                            <td>@teacher.Subject</td>
                            <td>
                                @{
                                    var base64 = Convert.ToBase64String(teacher.Image);
                                    var imgsrc = String.Format("data:image/png;base64,{0}", base64);
                                }
                                <img src="@imgsrc" width="55" height="55" style="margin-left:20px;" />
                            </td>
                            <td>
                                <a href="@Url.Action("RecoverTeachers","Trash",new {id=teacher.ID })" class="btn btn-primary btn-sm" style="color:white"><i class="fa fa-undo fa-sm"></i></a>
                                <a data-id="@teacher.ID" class="btn btn-danger btn-sm js-delete" style="color:white"><i class="fa fa-trash fa-sm"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

SchoolWeb/Admin/Views/Trash/Index.cshtml
@model Admin.ViewModels.StudentsTeachersMarksViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

@Html.Partial("DeletedTeachers", Model.Teachers)
@Html.Partial("DeletedStudents", Model.Students)
@Html.Partial("DeletedMarks", Model.Marks)

@section scripts{
    <script>
        $(document).ready(function () {
            $("#mark ").on("click", ".js-delete", function () {
                var button = $(this);
                bootbox.confirm("Bu məlumatı silməyə əminsinizmi?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "/Trash/RemoveMarks/" + button.attr("data-id"),
                            method: "GET",
                            success: function () {
                                button.parents("tr").remove();
                            }
                        });
                    }
                });
            });
        });
    </script>
    @*<script>
        $(document).ready(function () {
            $("#student ").on("click", ".js-delete", function () {
                var button = $(this);
                bootbox.confirm("Bu məlumatı silməyə əminsinizmi?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "/Trash/RemoveStudents/" + button.attr("data-id"),
                            method: "GET",
                            success: function () {
                                button.parents("tr").remove();
                            }
                        });
                    }
                });
            });
        });
    </script>*@
    <script>
        $(document).ready(function () {
            $("#teacher ").on("click", ".js-delete", function () {
                var button = $(this);
                bootbox.confirm("Bu məlumatı silməyə əminsinizmi?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "/Trash/RemoveTeachers/" + button.attr("data-id"),
                            method: "GET",
                            success: function () {
                                button.parents("tr").remove();
                            }
                        });
                    }
                });
            });
        });
    </script>
}