SchoolWeb/Admin/Controllers/ClassController.cs
using Admin.Constants;
using Admin.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Admin.Controllers
{
    [Authorize(Roles = "Admin,User,Teacher")]
    public class ClassController : Controller
    {
        // GET: Class
        public ActionResult Index()
        {
            using (var ctx=new DataContext())
            {
                var classes = ctx.TableClasses.Where(m => m.Status == Enums.Status.Active).ToList();
                return View(classes);
            }
        }

        public ActionResult Create()
        {
            var model = new TableClass();
            return View("ClassForm", model);
        }

        public ActionResult Update(int id)
        {
            using (var ctx=new DataContext())
            {
                var classes = ctx.TableClasses.FirstOrDefault(x => x.ID == id);
                return View("ClassForm",classes);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(TableClass _class)
        {
            using (var ctx = new DataContext())
            {
                if (!ModelState.IsValid)
                {
                    return View("ClassForm");
                }
                if (_class.ID == 0)
                {
                    _class.Status = Enums.Status.Active;
                    _class.CreatedDate = DateTime.Now;
                    ctx.TableClasses.Add(_class);
                }
                else
                {
                    _class.CreatedDate = DateTime.Now;
                    ctx.Entry(_class).State = EntityState.Modified;
                }
                ctx.SaveChanges();
            }
            return RedirectToAction("index");
        }

        public ActionResult Delete(int id)
        {
            using (var ctx = new DataContext())
            {
                var deletedclass = ctx.TableClasses.FirstOrDefault(x => x.ID == id);
                deletedclass.Status = Enums.Status.Deleted;
                ctx.Entry(deletedclass).State = EntityState.Modified;
                ctx.SaveChanges();
            }
            return RedirectToAction("index");
        }
    }
}

SchoolWeb/Admin/Controllers/StudentController.cs
using Admin.Constants;
using Admin.Models;
using Admin.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace Admin.Controllers
{
    [Authorize(Roles = "Admin,User,Teacher")]
    public class StudentController : Controller
    {
        DataContext ctx = new DataContext();
        public ActionResult Index()
        {
            var students = ctx.Students.Where(s => s.Status == Enums.Status.Active).ToList();
            return View(students);
        }

        public ActionResult ShowsStudents(int id)
        {
            var students = ctx.Students.Where(x => x.ClassID == id && x.Status == Enums.Status.Active).ToList();
            return PartialView(students);
        }

        public ActionResult Create()
        {
            var model = new StudentClassViewModel()
            {
                Classes = ctx.TableClasses.Where(x => x.Status == Enums.Status.Active).ToList(),
                Student = new Student()
            };
            return View(model);
        }

        public ActionResult Update(int id)
        {
            var student = ctx.Students.FirstOrDefault(x => x.ID == id);
            if (student == null)
                return HttpNotFound();

            var model = new StudentClassViewModel()
            {
                Classes = ctx.TableClasses.ToList(),
                Student = student
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Student student, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                var model = new StudentClassViewModel()
                {
                    Classes = ctx.TableClasses.ToList(),
                    Student = student
                };
                return View("Create", model);
            }
            if (student.ID == 0)
            {
                if (file != null && file.ContentLength > 0)
                {
                    student.Image = new byte[file.ContentLength];
                    file.InputStream.Read(student.Image, 0, file.ContentLength);
                    student.Status = Enums.Status.Active;
                    student.CreatedDate = DateTime.Now;
                    ctx.Students.Add(student);
                }
                else
                {
                    ViewBag.message = "Şəkil daxil edilməlidir";
                    var model = student;
                    return View("Create", model);
                }

            }
            else if (!ModelState.IsValid)
            {
                var model = new StudentClassViewModel()
                {
                    Classes = ctx.TableClasses.ToList(),
                    Student = student
                };
                return View("Update", model);
            }
            else if (file != null && file.ContentLength > 0)
            {
                student.Image = new byte[file.ContentLength];
                file.InputStream.Read(student.Image, 0, file.ContentLength);
                student.CreatedDate = DateTime.Now;
                ctx.Entry(student).State = EntityState.Modified;
            }
            else
            {
                student.CreatedDate = DateTime.Now;
                ctx.Entry(student).State = EntityState.Modified;
            }
            ctx.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var deletedstudent = ctx.Students.FirstOrDefault(x => x.ID == id);
            deletedstudent.Status = Enums.Status.Deleted;
            ctx.Entry(deletedstudent).State = EntityState.Modified;
            ctx.SaveChanges();
            return RedirectToAction("index");
        }
    }
}

SchoolWeb/Admin/Controllers/TeachersClassesController.cs
using Admin.Constants;
using Admin.Models;
using Admin.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace Admin.Controllers
{
    [Authorize(Roles = "Admin,User,Teacher")]
    public class TeachersClassesController : Controller
    {
        DataContext ctx = new DataContext();
        // GET: StudentsClasses
        public ActionResult Index()
        {
            var teacherclasses = ctx.TeachersClasses.ToList();
            return View(teacherclasses);
        }
        public ActionResult ShowTeachers(int id)
        {
            var teachersclasses = ctx.TeachersClasses.Where(x => x.ClassID == id).ToList();
            return PartialView(teachersclasses);
        }

        public ActionResult ShowClasses(int id)
        {
            var teachersclasses = ctx.TeachersClasses.Where(x => x.TeacherID == id).ToList();
            return PartialView(teachersclasses);
        }

        public ActionResult Create()
        {
            var model = new TeachersClassesViewModel()
            {
                tableclasses = ctx.TableClasses.Where(x => x.Status == Enums.Status.Active).ToList(),
                teachers = ctx.Teachers.Where(x => x.Status == Enums.Status.Active).ToList(),
                teachersClasses=new TeachersClasses()
            };
            return View("TeachersForm",model);
        }

        public ActionResult Update(int id)
        {
            var model = new TeachersClassesViewModel()
            {
                teachers = ctx.Teachers.ToList(),
                tableclasses = ctx.TableClasses.ToList(),
                teachersClasses = ctx.TeachersClasses.FirstOrDefault(x => x.ID == id)
            };
            return View("TeachersForm", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(TeachersClasses teachersclasses)
        {
            if (!ModelState.IsValid)
            {
                var model = new TeachersClassesViewModel()
                {
                    teachers=ctx.Teachers.ToList(),
                    tableclasses=ctx.TableClasses.ToList()
                };
                return View("TeachersForm");
            }
            if (teachersclasses.ID == 0)
            {
                ctx.TeachersClasses.Add(teachersclasses);
            }
            else
            {
                ctx.Entry(teachersclasses).State = EntityState.Modified;
            }
            ctx.SaveChanges();
            return RedirectToAction("index");
        }

        public ActionResult Delete(int id)
        {
            var deletedteacherclasses = ctx.TeachersClasses.FirstOrDefault(x => x.ID == id);
            ctx.TeachersClasses.Remove(deletedteacherclasses);
            ctx.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

SchoolWeb/Admin/Views/Class/ClassForm.cshtml
@model Admin.Models.TableClass
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

@using (Html.BeginForm("Save", "Class", FormMethod.Post))
{
    <div class="content container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    @Html.LabelFor(m => m.ClassNo)
                    @Html.TextBoxFor(m => m.ClassNo, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m=>m.ClassNo)
                </div>
                @Html.HiddenFor(m => m.ID)
                @Html.AntiForgeryToken()
                <button type="submit" class="btn btn-primary">Yadda saxla</button>
            </div>
        </div>
    </div>
}

SchoolWeb/Admin/Views/Class/Index.cshtml
@model List<Admin.Models.TableClass>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="content container-fluid">
    <div class="row">
        <div class="col-sm-12">
            @if (User.IsInRole("Admin"))
            {
                @Html.ActionLink("Yeni Sinif", "Create", null, new { @class = "btn btn-success Addbtn" })
            }
            <table id="dttable" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Sinif Nömrəsi</th>
                        @if (User.IsInRole("Admin"))
                        {
                            <th></th>
                        }
                        <th></th>
                        <th></th>
                    </tr>
                </thead>

                <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>Sinif Nömrəsi</th>
                        @if (User.IsInRole("Admin"))
                        {
                            <th></th>
                        }
                            <th></th>
                            <th></th>
                        </tr>
                </tfoot>

                <tbody>
                    @foreach (var classes in Model)
                    {
                    <tr>
                        <td>@classes.ID</td>
                        <td>@classes.ClassNo</td>
                        @if (User.IsInRole("Admin"))
                        {
                            <td>
                                <a href="@Url.Action("Update", "Class", new { id = classes.ID })" class="btn btn-primary btn-sm" style="color:white"><i class="fa fa-pen fa-sm"></i></a>
                                <a data-id="@classes.ID" class="btn btn-danger btn-sm js-delete" style="color:white"><i class="fa fa-trash fa-sm"></i></a>
                            </td>
                        }
                            <td>
                                @Ajax.ActionLink("Şagirdləri Göstər", "ShowsStudents", "Student", new { id = classes.ID }, new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "StudentList" }, new { @class = "btn btn-primary" })
                            </td>
                            <td>
                                @Ajax.ActionLink("Müəllimləri Göstər", "ShowTeachers", "TeachersClasses", new { id = classes.ID }, new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "TeacherList" }, new { @class = "btn btn-primary" })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <div id="StudentList"></div>
            <div id="TeacherList"></div>
        </div>
    </div>
</div>

@section styles{
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
}

@section scripts{
    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>*@
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/Scripts/MyDataTable.js"></script>

    <script>
        $(document).ready(function () {
            $("#dttable ").on("click", ".js-delete", function () {
                var button = $(this);
                bootbox.confirm("Bu məlumatı silməyə əminsinizmi?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "/class/Delete/" + button.attr("data-id"),
                            method: "GET",
                            success: function () {
                                button.parents("tr").remove();
                            }
                        });
                    }
                });
            });
        });
    </script>
}